name: Manual Azure build for STGN

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
jobs:
  azure-image-build:
    defaults:
      run:
        working-directory: runner
    strategy:
      matrix:
        variants: [ azure-image ]
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Run az commands'
        run: |
          az account show
          az group list
      - uses: actions/checkout@v3
      - name: Download packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip
          unzip packer_1.8.0_linux_amd64.zip
          chmod +x packer
          cp -R ami/packer/* .
      - name: Run packer
        run: |
          VERSION=${{ github.run_number }}
          ./packer build -var build_id=$VERSION ${{ matrix.variants }}.json
